calorie_compass/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('users.urls', namespace='users')),
    path('', include ('meals_tracker.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

meals_tracker/urls.py
from django.urls import path
from meals_tracker.views import about, home, calorie_calc, MealView

app_name = 'meals_tracker'

urlpatterns = [
    path('', home, name = "home_page"),
    path('about/', about, name="about_page"),
    path('calorie_calculation/', calorie_calc, name="calorie_calc"),
    path('meals/', MealView.as_view(), name="meals_list"),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('profile/', views.profile_edit, name='profile_edit'),
    path('user/<str:username>/delete', views.delete_user, name='delete-user'),

]

meals_tracker/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.urls import reverse


class Meals(models.Model):
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    food_items = models.TextField()
    calories = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        if isinstance(self.calories, float):
            self.calories = round(self.calories)
        super(Meals, self).save(*args, **kwargs)

    def __str__(self):
        """Return a string representation of the meals."""
        return self.name

    class Meta:
        """The plural name used in the admin interface for the model."""
        verbose_name_plural = "Meals"

    def get_absolute_url(self):
        return reverse('meals_tracker:meals_tracking', kwargs={'slug': self.slug})

users/models.py
from django.db import models
from PIL import Image
from pathlib import Path
import os
from django.contrib.auth.models import User


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def image_upload(instance, filename):
    ext = filename.split(".")[-1]
    folder = BASE_DIR / 'media' / 'profile'
    img_list = os.listdir(folder)
    for img in img_list:
        if str(instance.user) in img:
            os.remove(folder / img)

    return f'profile/{instance.user}.{ext}'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=image_upload, default='profile/default.jpg')
    age = models.IntegerField(default=0)
    hight = models.DecimalField(default=0, max_digits=4, decimal_places=1)
    weight = models.DecimalField(default=0, max_digits=4, decimal_places=1)

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)
        rgb_img = img.convert('RGB')
        if rgb_img.height > 300 or rgb_img.width > 300:
            output_size = (300, 300)
            rgb_img.thumbnail(output_size)
            rgb_img.save(self.image.path)

    def full_name(self):
        return f"{self.user.first_name} {self.user.last_name}"

meals_tracker/forms.py
from django import forms
from meals_tracker.models import Meals


class MealForm(forms.ModelForm):

    class Meta:
        model = Meals
        fields = ['name', 'food_items']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['food_items'].widget.attrs.update({'placeholder': 'Enter your food items with only one type of separator (commaspace, space, or plus sign) to separate food items'})

users/forms.py
from users.models import Profile
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from allauth.account.forms import LoginForm, SignupForm


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [('first_name'), ('last_name')]


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [('image'), ('age'), ('weight'), ('hight')]

meals_tracker/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from meals_tracker.models import Meals
from django.contrib.auth.mixins import LoginRequiredMixin
from meals_tracker.forms import MealForm
from django.http import JsonResponse
from django.conf import settings
from django.template.defaulttags import register
from django.contrib import messages
from django.urls import reverse


@register.filter(name='split')
def split(value, key):
    """
        Returns the value turned into a list.
    """
    return value.split(key)

# Create your views here.
def home(request):
    return render(request, 'meals_tracker/home.html')


def about(request):
    return render(request, 'meals_tracker/about.html')


def calorie_calc(request):
    return render(request, 'meals_tracker/calorie_calc.html')


class MealView(LoginRequiredMixin, View):
    template_name = 'meals_tracker/meal-tracking.html'


    def get(self, request, *args, **kwargs):
        form = MealForm()
        return self.form_invalid(request, form)

    def post(self, request, *args, **kwargs):
        if request.POST.get('_method') == 'delete':
            return self.delete(request, *args, **kwargs)

        form = MealForm(request.POST)
        if form.is_valid():
            new_meal = form.save(commit=False)
            new_meal.user = request.user
            new_meal.calories = request.POST.get('calories', 0)
            new_meal.food_items = request.POST.get('food_items')
            new_meal.save()
            return JsonResponse({'redirect_url': reverse('meals_tracker:meals_list')})

        return self.form_invalid(request, form)


    def form_invalid(self, request, form):
        meals = Meals.objects.filter(user=request.user)
        selected_meal = None
        slug = request.GET.get('slug')

        if slug:
            selected_meal = get_object_or_404(Meals, slug=slug, user=request.user)

        return render(request, self.template_name, {
            'meals': meals,
            'selected_meal': selected_meal,
            'form': form,
            'calorie_ninjas_api_key': settings.CALORIE_NINJAS_API_KEY
        })


    def delete(self, request, *args, **kwargs):
        slug = request.POST.get('meal_slug')
        meal = get_object_or_404(Meals, slug=slug, user=request.user)
        meal.delete()
        messages.success(request, f'The {slug} has been deleted successfully !')
        return redirect('meals_tracker:meals_list')

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.urls import reverse
from .forms import UserUpdateForm, ProfileUpdateForm


@login_required
def profile_edit(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, 'Your account has been updated !')
            return redirect('users:profile_edit')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form,
    }
    return render(request, 'users/profile_edit.html', context)


@login_required
def delete_user(request, username):
    user = User.objects.get(username=username)
    if request.user == user:
        if request.method == 'POST':
            user.delete()
            messages.success(request, 'Your account has been deleted successfully !')
            return redirect('/')
        context = {'username': username}
        return render(request, 'users/delete_user.html', context)
    else:
        messages.warning(request, 'Oooops you do not have permission to do that!')
        return redirect('users:profile_edit')

meals_tracker/templates/meals_tracker/about.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}
  <link rel="stylesheet" href="{% static 'css/about-style.css' %}" />
{% endblock styles %}

{% block extra_head %}
  - About-Us
{% endblock extra_head %}

{% block content %}
    <main>
      <h1>About Us</h1>
      <p>
        We are about helping people achieve their wellness goal. Calorie Compass
        is where we share our thoughts, experience, and inspiration to motivate
        you in your weight loss journey. We believe that with the right tool and
        support, anyone can achieve their goals. Take a look around our site and
      </p>

      <h1>LET’S START THIS JOURNEY TOGETHER!</h1>
    </main>
{% endblock content %}

meals_tracker/templates/meals_tracker/calorie_calc.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}
  <link rel="stylesheet" href="{% static 'css/calorie-cal-style.css' %}" />
{% endblock styles %}

{% block extra_head %}
  - Calorie Calculation
{% endblock extra_head %}

{% block content %}
    <div class="container">
      <h1>Calorie Calculator</h1>
      <div class="search-container">
        <form class="d-flex" role="search" method="post">
          <input
            class="form-control me-2"
            type="text"
            placeholder="Enter Your Food per grams or unit (100 grams of egg OR one egg) ..."
            aria-label="Search"
            name="query"
          />
          <button class="btn btn-outline-dark" type="submit">Search</button>
        </form>
      </div>

      <div class="loading-indicator" style="display: none">
        <img src="images/loading.gif" alt="Loading..." />
      </div>

      <h1 class="nutrition-report-display">
        The Calories in <span class="food-name"></span> are
        <span class="calorie-amount"></span> calories
      </h1>

      <div class="pie-chart-container">
        <canvas id="nutritionPieChart"></canvas>
      </div>

      <div class="nutrition-report">
        <h2>Nutritions Facts</h2>
        <table class="table table-secondary">
          <thead>
            <tr>
              <th scope="col"></th>
              <th scope="col">Unit (g or mg)</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            <tr class="table-light">
              <th scope="row">Serving Size</th>
              <td class="size-report"></td>
              <td class="size-report-percentage"></td>
            </tr>
            <tr class="table-warning">
              <th scope="row">Total Carbohydrates</th>
              <td class="carb-report"></td>
              <td class="carb-report-percentage"></td>
            </tr>
            <tr class="table-warning">
              <th scope="row">Fiber</th>
              <td class="fiber-report"></td>
              <td class="fiber-report-percentage"></td>
            </tr>
            <tr class="table-warning">
              <th scope="row">Sugar</th>
              <td class="sugar-report"></td>
              <td class="sugar-report-percentage"></td>
            </tr>
            <tr class="table-success">
              <th scope="row">Proteins</th>
              <td class="proteins-report"></td>
              <td class="proteins-report-percentage"></td>
            </tr>
            <tr class="table-success">
              <th scope="row">Sodium</th>
              <td class="sodium-report"></td>
              <td class="sodium-report-percentage"></td>
            </tr>
            <tr class="table-success">
              <th scope="row">Potassium</th>
              <td class="potassium-report"></td>
              <td class="potassium-report-percentage"></td>
            </tr>
            <tr class="table-danger">
              <th scope="row">Total Fats</th>
              <td class="fats-report"></td>
              <td class="fats-report-percentage"></td>
            </tr>
            <tr class="table-danger">
              <th scope="row">Saturated Fats</th>
              <td class="Sfats-report"></td>
              <td class="Sfats-report-percentage"></td>
            </tr>
            <tr class="table-danger">
              <th scope="row">Cholesterol</th>
              <td class="cholesterol-report"></td>
              <td class="cholesterol-report-percentage"></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
{% endblock content %}

{% block scripts %}
  <script src="{% static 'js/calorie-cal.js' %}"></script>
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
{% endblock scripts %}

meals_tracker/templates/meals_tracker/home.html
{% extends 'base.html' %}

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap5 %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta
            name="keywords"
            content="HTML, CSS, JS, Django, Python, calorie, health, calorie calculation"
        />
        <meta name="robots" content="index, follow" />
        <meta name="description"
            content="Calorie Compass is your ultimate guide in your weight loss journey. With our app, you can easily track your daily calorie intake, create your profile, add meals, and track your progress toward daily and weekly calorie and weight loss goals. Our app also suggests healthy meals that align with your calorie goals"
        />
        <meta property="og:title" content="Karima Mahmoud & Bahy Allam Portfolio" />
        <meta property="og:image" content="logo.png" />
        <meta property="og:url" content="https://bahy.pythonanywhere.com/" />
        <meta property="og:type" content="website" />
        <meta name="calorie-ninjas-api-key" content="{{ calorie_ninjas_api_key }}">
        <!-- bootstraps -->
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
        />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
              integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
              crossorigin="anonymous"
        />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
        <script
                src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
                crossorigin="anonymous">

        </script>
        {% block styles %}
            <link rel="stylesheet" href="{% static 'css/index-style.css' %}" />
        {% endblock styles %}
        <link rel="icon" href="{% static 'img/logo.png' %}" type="image/png" />
        <title>
            {% block head_title %}
            Calorie Copmass
            {% endblock head_title %}
            {% block extra_head %}
            {% endblock extra_head %}
        </title>
    </head>
    <body>
        {% block header %}
            <header class="nav-bar">
                <nav class="navbar navbar-expand-lg bg-body-tertiary">
                    <div class="container-fluid">
                        <a class="navbar-brand" href="/">
                            <img class="logo" src="{% static 'img/logo.png' %}" alt="Calorie Compass Logo"/>
                        </a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                                data-bs-target="#navbarNav" aria-controls="navbarNav"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse align-right" id="navbarNav">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                                </li>

                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle"
                                       href="" role="button"
                                       data-bs-toggle="dropdown" aria-expanded="false">Our Products</a>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a class="dropdown-item" href="{% url 'meals_tracker:calorie_calc' %}">Calorie Calculation</a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" href="{% url 'meals_tracker:meals_list'%}">Daily Meal Tracker</a>
                                        </li>
                                    </ul>
                                </li>

                                {% if user.is_authenticated %}
                                        <li class="nav-item">
                                            <a class="nav-link active" aria-current="page" href="{% url 'users:profile_edit' %}">Profile</a>
                                        </li>
                                    {% url 'account_logout' as logout_url %}
                                    {% if logout_url %}
                                        <li class="nav-item">
                                            <a class="nav-link active" aria-current="page" href="{% url 'account_logout' %}">Sign Out</a>
                                        </li>
                                    {% endif %}
                                {% else %}
                                    {% url 'account_login' as login_url %}
                                    {% if login_url %}
                                        <li class="nav-item">
                                            <a class="nav-link active" aria-current="page" href="{{ login_url }}">Sign in</a>
                                        </li>
                                    {% endif %}
                                    {% url 'account_signup' as signup_url %}
                                    {% if signup_url %}
                                        <li class="nav-item">
                                            <a class="nav-link active" aria-current="page" href="{{ signup_url }}">SignUp</a>
                                        </li>
                                    {% endif %}
                                {% endif %}
                                <li class="nav-item">
                                    <a class="nav-link active" href="{% url 'meals_tracker:about_page' %}">About Us</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </header>
        {% endblock header %}

        {% block messages %}
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} text-center">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endblock messages %}

        {% block content %}
            <div class="intro-page flex">
                <h1 class="text-center">Your Health Companions</h1>
                <h3 class="text-center">Track Your Progress</h3>
                <p class="text-center">
                  Calorie Compass is your ultimate guide in your weight loss journey.
                  With our app, you can easily track your daily calorie intake, create
                  your profile, add meals, and track your progress toward daily and
                  weekly calorie and weight loss goals. Our app also suggests healthy
                  meals that align with your calorie goals.
                </p>
                <a href="#products"><button class="text-center">Our Products</button></a>
            </div>
            <main class="main-body">
                <h1 class="text-center p-3 our-products" id="products">Our Products</h1>
                <div class="container-fluid meal-tracking flex">
                  <div class="row">
                    <div class="col-md-6 p-3">
                      <p>
                        <b>Daily Meal Tracking</b> is a fundamental feature of our app.
                        With meal tracking, users can easily log their daily food
                        intake. Whether it’s breakfast, lunch, dinner, or snacks, our
                        app allows users to record the details of each meal. By keeping
                        track of their meals, users gain insights into their calorie
                        consumption patterns, helping them make informed decisions about
                        their diet.
                      </p>
                    </div>
                    <div class="col-md-6 p-3">
                      <a href="{% url 'meals_tracker:meals_list'%}"
                        ><img
                          src="{% static 'img/meal-suggestion.png' %}"
                          alt=""
                          class="img-fluid custom-main-image"
                      /></a>
                    </div>
                  </div>
                </div>
                <div class="container-fluid calorie-calc">
                  <div class="row">
                    <div class="col-md-6 p-3">
                      <a href="{% url 'meals_tracker:calorie_calc' %}">
                        <img
                          src="{% static 'img/meal-tracker.png' %}"
                          alt=""
                          class="img-fluid custom-main-image"
                      /></a>
                    </div>
                    <div class="col-md-6 p-3">
                      <p>
                        <b>Calculating Daily Calorie Intake</b> is crucial for anyone
                        aiming to manage their weight. Our app simplifies this process.
                        Users input their personal details (such as age, weight, and
                        height), and our algorithm computes their daily caloric needs.
                        It’s a powerful tool for understanding how many calories you
                        should consume to achieve your health and fitness goals.
                      </p>
                    </div>
                  </div>
                </div>
            </main>
        {% endblock content %}
        {% block extra_body %}
        {% endblock extra_body %}
        {% block footer %}
            <footer>
                <div class="contacts" id="contacts">
                    <div class="row">
                      <div class="col-6">
                        <h1>
                          Keep <br />
                          In <br />Touch!
                        </h1>
                      </div>
                      <div class="col-6">
                        <div class="social-contacts">
                          <a
                            href="https://github.com/BahyAllaAllam/Calorie-compass"
                            target="_blank"
                            ><i class="fab fa-github mb-4 mt-4"></i>
                          </a>
                          <br />
                          <a href="#" target="_blank"
                            ><i class="fab fa-linkedin mb-4"></i
                          ></a>
                          <br />
                          <a href="mailto:" target="_blank">
                            <i class="fas fa-envelope mb-4"></i>
                          </a>
                          <br />
                          <a href="https://wa.me/2001112302971" target="_blank">
                            <i class="fa-brands fa-whatsapp mb-4"></i>
                          </a>
                        </div>
                      </div>
                    </div>
                </div>
                <div class="copyRights">
                    <p>
                        Copyright ©2024 Calorie Compass
                        <br>
                        All Rights Reserved
                        <br>
                        Build by <a href="https://github.com/KariMaa-MahMoud" target="_blank"> Karima Mahmoud</a> &
                        <a href="https://github.com/BahyAllaAllam" target="_blank"> Bahy Allam</a>
                    </p>
                </div>
            </footer>
        {% endblock footer %}
        {% block scripts %}
            <script src="{% static 'js/scripts.js' %}"></script>
        {% endblock scripts %}
    </body>
</html>

templates/base_generic.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
{% endblock styles %}

{% block header %}
{% endblock header %}

{% block content %}
<div class="container">
    <a href="/">
        <img class="logo" src="{% static 'img/logo.png' %}" alt="Calorie Compass Logo"/>
    </a>
    {% block auth_content %}
    {% endblock auth_content %}
</div>
{%  endblock content%}

{% block footer %}
{% endblock footer %}

templates/base_reauthenticate.html
{% extends "base_generic.html" %}
{% load allauth %}

{% block extra_head %}
    - Confirm Access
{% endblock extra_head %}

{% block auth_content %}
    {% element h1 %}
        Confirm Access
    {% endelement %}
    {% element p %}
        Please reauthenticate to safeguard your account.
    {% endelement %}
    {% block reauthenticate_content %}{% endblock %}
    {% if reauthentication_alternatives %}
        {% element hr %}
        {% endelement %}
        {% element h2 %}
            Alternative options
        {% endelement %}
        <ul>
            {% for alt in reauthentication_alternatives %}
                <li>
                    <a href="{{ alt.url }}">{{ alt.description }}</a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock auth_content %}

users/templates/users/delete_user.html
{% extends "base_generic.html" %}
{% load allauth i18n %}
{% load static %}

{% block extra_head %}
  - Delete {{username}} account
{% endblock extra_head %}

{% block auth_content %}
    {% element h1 %}
        Delete Confirmation
    {% endelement %}
    {% element p %}
        Are you sure you want to delete your account "{{ user.username }}"?
    {% endelement %}
    <form method="POST">
        {% csrf_token %}
        {{ redirect_field }}
        <input class="btn btn-outline-danger" type="submit" value="Yes, Delete">
        <a class="btn btn-outline-success" href="{% url 'users:profile_edit'%}">Cancel</a>
    </form>

{% endblock auth_content %}

users/templates/users/profile_edit.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap5 %}

{% block extra_head %}
  - {{user.username}} Profile
{% endblock extra_head %}

{% block content %}
    <div class="content">
        <div class="col-md-8">
            <div class="content-section">
                <div class="media">
                    <img class="rounded-circle account-img" src="{{ user.profile.image.url }}" alt="{{ user.username }} Profile Picture">
                    <div class="media-body">
                        <h2 class="account-heading">
                            {{user.username}}
                        </h2>
                        <p class="text-secondary">{{user.email}}</p>
                        <a class="btn btn-outline-success btn-sm mt-1 mb-1" href="{% url 'account_change_password' %}">Change Password</a>
                        <a class="btn btn-outline-success btn-sm mt-1 mb-1" href="{% url 'account_email' %}">Change Email</a>
                        <a class="btn btn-outline-danger btn-sm mt-1 mb-1" href="{% url 'users:delete-user' user.username %}">Delete Account</a>
                    </div>
                </div>
                <br>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4 text-center">Profile Info</legend>
                        {% bootstrap_form u_form %}
                        {% bootstrap_form p_form %}
                    </fieldset>
                    <button class="btn btn-outline-success w-100 mt-4" type="submit">Update</button>
                    <a class="btn btn-outline-danger w-100 mt-4" href="/">Cancel</a>
                </form>
            </div>
        </div>
    </div>

{%  endblock content %}